### ISSUE TITLE
ブロック「ステップ」→画像の位置「右側」のレイアウトが崩れる

### ISSUE THREAD

**Issue by yamasakidaisuke** [inc2734/snow-monkey-blocks#113]
複数の環境で試してみましたが画像が右側に配置されず、崩れました。
バージョン 3.0.7
テスト環境
https://yamasakidaisuke.com/pc/snowmonkey/snow-monkey-blocks.html

**Comment by inc2734** [comment]
ご報告たすかります、ありがとうございます！
