### ISSUE TITLE
かっこいい動画ヘッダーが作れるようなブロックの要望

### ISSUE THREAD

**Issue by megane9988** [inc2734/snow-monkey-blocks#123]
https://six.abejainc.com/
で利用されているものなのですが、画面幅に応じて常に縦横100%になるように、動画が表示されて流れます。

こういうダイナミックなブロックがあると嬉しいです。

![image](https://user-images.githubusercontent.com/1205958/53865723-3a788f00-4033-11e9-9bd0-04b24c3795c1.png)

該当のページは以下を使っているぽいですが。
https://pupunzi.com/mb.components/mb.YTPlayer/demo/demo.html

jQueryなので見栄えの参考として、考えていただければと！

**Comment by inc2734** [comment]
WordPress コアの機能で言えば、カスタムヘッダーに動画埋め込んだときみたいなことなのかなぁと思うのですが、果たしてブロックとしてつくったときに上記ページのような感じにできるのかがちょっと気になるところです…。

動画背景が使いたいなぁとは思ったこともあって、セクション（背景画像あり）ブロックの動画版みたいなのをつくれば良いのかなぁと思ったりしてはいました。jQuery はブロックエディターと相性がわるいので、やるなら TwentySeventeen みたいに普通に iframe で動画埋め込む感じが良いかなぁと。
