### ISSUE TITLE
アコーディオンブロックに矢印をつける

### ISSUE THREAD

**Issue by inc2734** [inc2734/snow-monkey-blocks#134]

**Comment by kmix-39** [comment]
矢印の方向を変更するとなるとsmb-accordion__item__titleのdivタグ内に<i>で矢印を記述するかなので、

input要素の.smb-accordion__item__controlを.smb-accordion__item__titleの前にする。
（checkbox要素がz-index:1なので、順序を変えても押す領域に影響は及ばない）
.smb-accordion__item__control要素より前の場合はCSSで.smb-accordion__item__titleが制御出来ない為。

smb-accordion__item__titleに矢印の付与をする。
.smb-accordion .smb-accordion__item__control:checked+.smb-accordion__item__bodyの変更を
.smb-accordion .smb-accordion__item__control:checked+.smb-accordion__item__title+.smb-accordion__item__bodyに変える。

後は同様にchecked時に矢印の向きを変更したcssを記述するなどで調整する。

とすれば、出来なくはなさそうな気がします。
HTMLの順番を変える程度なのでまだdeprecatedは書きやすい…かと。
:checkedを変えてるのがどこに記載しているかがちょっと解ってませんが。

もうちょいスマートなやり方はありそうなので、ちょっと思いついたら書きます。

**Comment by inc2734** [comment]
HTML と CSS 考えてみますので少々お待ちを。

**Comment by kmix-39** [comment]
お手数おかけします。
それだけあれば、多分後はblockの調整とDeprecatedだけになるはずなんで
後はこちらで調整します。

他のアコーディオンを閉じるって機能も、jsで他のチェックを外すってやるようにするだけかと思うので、
余裕あればそれも。

**Comment by inc2734** [comment]
kmix-39 さんが書かれてたとおり、 checkbox の位置は移動させないとダメですねぇ。

```
<div class="wp-block-snow-monkey-blocks-accordion smb-accordion">
  <div class="wp-block-snow-monkey-blocks-accordion--item smb-accordion__item">
    <input type="checkbox" class="smb-accordion__item__control">
    <div class="smb-accordion__item__title">
      <span>アコーディオン</span>
      <i class="fas fa-angle-down"></i>
    </div>
    <div class="smb-accordion__item__body">
      <p>あいうえお</p>
    </div>
  </div>
</div>
```

```
.smb-accordion .smb-accordion__item__control:checked + .smb-accordion__item__body,
.smb-accordion .smb-accordion__item__control:checked + .smb-accordion__item__title + .smb-accordion__item__body {
  display:block;
}
.smb-accordion .smb-accordion__item__control:checked + .smb-accordion__item__title .fa-angle-down {
  transform: rotate(180deg);
}
.smb-accordion__item__title .fa-angle-down {
  transition: transform .1s;
  flex: 0 0 auto;
}
.smb-accordion__item__title {
  display: flex;
  align-items: center;
}
.smb-accordion__item__title span {
  flex: 1 1 auto;;
}
```

**Comment by kmix-39** [comment]
> checkbox の位置は移動させないとダメですねぇ

やはり、そうなりますか…。
jsで親要素取ってそこのtitleとか取ってやるのは、あまりにもカッコ悪すぎるので、
+ が乱立するCSSの方がまだ良いかと思ってました。
…CSSにも前の要素を取得する為の要素の省略子が実装されてあれば良かったんですけどね…。

一度、いただいたHTMLとCSSの形で一度実装してみます。有難うございます。

**Comment by inc2734** [comment]
CSS は今から書いて push します！

**Comment by kmix-39** [comment]
TIA

**Comment by inc2734** [comment]
先の HTML はちょっと問題あるので、クラスふるようにしました。

```
<div class="wp-block-snow-monkey-blocks-accordion smb-accordion">
  <div class="wp-block-snow-monkey-blocks-accordion--item smb-accordion__item">
    <input type="checkbox" class="smb-accordion__item__control">
    <div class="smb-accordion__item__title">
      <span class="smb-accordion__item__title__label">アコーディオン</span>
      <div class="smb-accordion__item__title__icon">
        <i class="fas fa-angle-down"></i>
      </div>
    </div>
    <div class="smb-accordion__item__body">
      <p>あいうえお</p>
    </div>
  </div>
</div>
```

**Comment by kmix-39** [comment]
では、そのHTMLでUpdate accordion cssの続きから実装します！

**Comment by kmix-39** [comment]
すみません、item落ちてましたよ

.smb-accordion__title__label

に、よいしょっと。

.smb-accordion__item__title__label

……HTMLの方が後なので気になりましたが、CSSの方のクラスにitem入れる形で修正してOKすよね？

**Comment by inc2734** [comment]
あ、ミスです…(TT
修正 OK です！

**Comment by kmix-39** [comment]
#135 にプルリクしています。ご確認お願いします。

…SMBの方ではdeprecatedを書いたのは初だったので、ちょっとおかしい所あるかもです。
deprecatedのattributesをschemaファイルにold_schema_バージョン番号…として書いて管理するって方が良かったかもですね。
マイグレーションとか色々使うとブロックの再編集時に重くなるようなので、出来るだけそう言うのを使わない設計も考えていきますorz

また、その辺りの仕様は、ワイワイ言えたら良いと思います。

SMBでのdeprecated、色々勉強出来ましたので今後は簡単なブロックの修正はdeprecatedと絡めつつ考えるようにします。（迷惑でなければ

**Comment by inc2734** [comment]
ありがとうございます、マージしました！

> deprecatedのattributesをschemaファイルにold_schema_バージョン番号…として書いて管理するって方が良かったかもですね。

Gutenberg プラグインにあわせたほうが良いと思っていて、あっちだと `deprecated` の中で `schema` 読み込んで、それを足したり引いたりしてましたので、Snow Monkey Blocks でも同じ感じにしてます。

**Comment by kmix-39** [comment]
あ、足したり引いたりってそう言う事だったのかと！…きちんと理解出来てませんでした。
次からはその形にします！
