### ISSUE TITLE
QとAの文字を書き換えられるように

### ISSUE THREAD

**Issue by kmix-39** [inc2734/snow-monkey-blocks#136]
縦書きで思ったことですが、
日本風なサイトだと「問」「解」や「質問」「回答」にしたい可能性もありそうな気がしました。

ただし、自由に変更できるのは何か変な感じなので、
制限を設ける場合はどう言うパターンを取るか考慮する必要あり。

**Comment by inc2734** [comment]
普通にテキストで表示しているだけなので、任意の文字を入力できるようにするのは問題なさそう。デザイン的にあまり文字を入れすぎると崩れたようになっちゃいますが、独自に CSS でデザインをカスタマイズしてでも入れたい、という場合もあるかもなので、制限をかけるというのも微妙な気はします。ちょっと考えます。

**Comment by kmix-39** [comment]
思い付いたら書いて頂くだけでも。実装はこちらでも出来ます。実際、制限と言うところが悩みなだけなんで。

後、説明の追加助かりました。
イシュー立てた後に、良い説明も英文も出来ずに放置してました(汗)
