### ISSUE TITLE
セクションの背景マスクの色の問題

### ISSUE THREAD

**Issue by kmix-39** [inc2734/snow-monkey-blocks#142]
（背景画像あり）と（背景動画あり）のセクションで発生する。
背景マスクの色の「クリア」を押して、クリア状態のまま再編集をするとブロックが壊れる。

**Comment by kmix-39** [comment]
色々試しましたが、

save時にmaskColorを見るが、クリア時は未定義となるので、
編集時の初期参照値は、defaultが代入され、結果としてbackground-color: ＃000として見られている感じがします。
それで結果が噛み合わないのでdeprecatedが処理されていますが、そこを変更したとしてもmaskColorがdefaultの＃000に上書きされる…（保存時のクリアを保てない）

テキストカラーも同様な問題が起こってますが、
テキストカラーがクリア時は、deprecatedでも上手くクリア値が適用されてます。（何故？？

もう少し検証が必要そうなので、また後日にも調査します…

**Comment by inc2734** [comment]
なるほど…。色を `setAttributes` するときに 空なら `transparent` を保存するとかですかねぇ（試してないので想像

**Comment by inc2734** [comment]
ちょっとみてみてますが、マスクの色とかは↑で良いとしても、文字色部分だと微妙ですね…。とりあえずマスクとか背景色部分だけやってみます。

**Comment by kmix-39** [comment]
いや、初期色が#000なんで、それやっても壊れたままなんです。
どう言うことかと言うと…

maskColorがクリアで保存→maskColorが定義されてない為、初期値の#000が代入された状態でsaveの記述されたデータと照合。（DBからのデータは定義がないのでstyle=記述が出ない、照合は#000でstyle記述が起こる）
なので、deprecatedが発生。

deprecatedできず、壊れる。

です。

**Comment by kmix-39** [comment]
書いてる間に返信がw

文字色についてはdeprecatedの中でstyle=で文字色を定義してないパターンがありますよね。
それのお陰でクリアのまま保存しても壊れません。背景の場合はstyle=が書かれたパターンしかないので起こる。
ただ、パターンを追加しても再編集時には上記の問題で#000でデフォルト値が初期化されるんで、
再編集時に値が#000で、編集復帰しちゃうんです。

これがちょっと悩ましいなって所ですね。

**Comment by inc2734** [comment]
今一応セクション背景画像ありと、背景動画ありのマスク部分について `setAttributes( { maskColor: value || 'transparent' } )` にするといけました。とりあえずこの issue はこの修正をとりこんだら閉じようかなと。

**Comment by kmix-39** [comment]
その修正だと、前のバージョンからのブロックだと壊れたままのような気がしますが、どうでしょうか？

一応、その修正での方針であれば、deprecatedでmaskColorのstyle記述を消しただけのパターンも加えておけば、前のバージョンからのブロックは#000で初期化された状態で再編集可能になりますので、それもやっておけば問題ない可能性…です。

**Comment by inc2734** [comment]
既存バージョンの場合クリアして保存した時点で壊れているわけで、今回のアップデートにより壊れるわけではないので大丈夫かなと。

> deprecatedでmaskColorのstyle記述を消しただけのパターンも加えておけば、前のバージョンからのブロックは#000で初期化された状態で再編集可能になりますので、それもやっておけば問題ない可能性…

最新版は `default: #000` で、deprecated 内のだけ `default` なしということですかね？

**Comment by kmix-39** [comment]
> 既存バージョンの場合クリアして保存した時点で壊れている

まあ、それは確かに。なので、

> 最新版は default: #000 で、deprecated 内のだけ default なしということですかね？

多分、そうです。
deprecatedの中のsaveの記述って、照合するDBの値になるので、style=の部分を消せば、既存バージョンのクリアして保存した壊れているパターンに一致するんで、既存のバージョンを#000の状態で最悪、再編集が可能になるかと。そういう風にしませんか？…って事です。
もう壊れているのをきちんと直すのは諦め…ですが、一応の保険をかけておこうかと。
（セクションブロックなので、これが壊れたら中身まで直すのが凄く大変なんですよ…）

ちょっと、これは伝わりにくかった所です（汗
