### ISSUE TITLE
「パネル」や「項目」の子要素の画像のAltを書き出してほしい

### ISSUE THREAD

**Issue by inc2734** [inc2734/snow-monkey-blocks#143]
https://snow-monkey.2inc.org/forums/topic/snow-monkey-blocks-%E3%80%8C%E3%83%91%E3%83%8D%E3%83%AB%E3%80%8D%E3%82%84%E3%80%8C%E9%A0%85%E7%9B%AE%E3%80%8D%E3%81%AE%E5%AD%90%E8%A6%81%E7%B4%A0%E3%81%AE%E7%94%BB%E5%83%8F%E3%81%AEalt%E3%82%92/

**Comment by kmix-39** [comment]
こちらで作業してますので、後ほどプルリクします。
（作業競合が起きないように、念の為報告）
