### ISSUE TITLE
styleのnullが出力される

### ISSUE THREAD

**Issue by kmix-39** [inc2734/snow-monkey-blocks#194]
スタイルに`color:null`で設定されている。`null`時はcolorスタイル設定をしないようにした方が良い？

**Comment by inc2734** [comment]
`null` にしてれば `style` が出力されない想定だったのですが出力されちゃってますかね…？

**Comment by kmix-39** [comment]
Safariだと`style="color:null"`ってデベロッパーツールにも出てきます。
スクレイピングのPHPで調べても出力されてるのでされてると思っていいかと。

他にも同じような所があるかは調べてみるので、issueを「styleのnullが出力される」に変えて
潰していければ良いかなと思いますー。

判明しているnullが出力される該当スタイル：

smb-list__icon の color

**Comment by inc2734** [comment]
おぉ、なるほど…。 `undefined` なら出力されなかったかも（はっきり覚えてませんが、書き換えた記憶があったりなかったり

**Comment by kmix-39** [comment]
`undefined`なら出力されなさそうな気がします。まあ、そこまで緊急性はないです。
`null`だとSafariも「そんなカラー定義はない」って感じでスタイルを除外して表示させてますし。

**Comment by kmix-39** [comment]
他のブロックでは当の問題は起こらないのを確認。

問題の原因は、

https://github.com/inc2734/snow-monkey-blocks/blob/a9a3efea0a58208189e65df153668b805ff1c4f4/block/list/_list.js#L12

で、変数文字列として`style="color:…`と、直接扱っているからだと思われます。

**Comment by inc2734** [comment]
なるほど！！
確かに他のブロックでは

```
const faqItemQestionLabelStyles = {
	color: questionColor || undefined,
};
```

こんな感じで無いときは `undefined` にして、かつオブジェクト形式で `style` 設定してますね。リストもそのように変更いれます！

**Comment by kmix-39** [comment]
その修正内容で問題ないと思います。他のアップデート時に対応していただければー。
