### ISSUE TITLE
"このページの子ページブロック"のタイトルを編集可能にしたい

### ISSUE THREAD

**Issue by hideokamoto** [inc2734/snow-monkey-blocks#195]
多分この辺だと思うのですが、「このページの子ページブロック」の見出しが「このページの子ページブ」なのを編集できるようにしたいです。
https://github.com/inc2734/snow-monkey-blocks/blob/master/block/child-pages/block.js#L27

あんまり「子ページ」という表記をサイトで使わないので、変えれるようにするか非表示にして自前でタイトルタグを入れるかしたい・・・

**Comment by inc2734** [comment]
一般の閲覧者がみえる表側の表示を帰れるようにしたい、ということですよね？ このページの子ページブロックは Snow Monkey のテンプレートを呼ぶようになっているので Snow Monkey 側のフックで書き換えが可能です。

例えば

```
add_filter(
	'snow_monkey_child_pages_title',
	function( $child_pages_title ) {
		return 'あいうえお';
	}
);
```

とか

```
add_filter(
	'snow_monkey_template_part_render',
	function( $html, $slug ) {
		if ( 'template-parts/content/child-pages' === $slug ) {
			$html = preg_replace(
				'|(<h2 class="p-child-pages__title c-entry-aside__title">[\t\s]*<span>)(.+?)(</span>[\t\s]*</h2>)|ms',
				'$1かきくけこ$3',
				$html
			);
		}
		return $html;
	},
	10,
	2
);
```

とかです。

そもそもをいえば、「このページの子ページ」という名称も微妙だなとは思うので、スタンダードな名称があれば全然デフォルトを変えるのは構わないです！
