### ISSUE TITLE
既にsmb等のslugがある場合のカテゴリー重複を除外する

### ISSUE THREAD

**Issue by kmix-39** [inc2734/snow-monkey-blocks#202]
```
public function _block_categories( $categories ) {
$slugs = array_column( $categories, 'slug' );
if ( !  in_array( 'smb', $slugs, true ) ) {
$categories[] = [
			'slug'  => 'smb',
			'title' => __( 'Snow Monkey Blocks', 'snow-monkey-blocks' )
								. ' '
								. __( '[Common blocks]', 'snow-monkey-blocks' ),
		];
}
if ( !  in_array( 'smb-section', $slugs, true ) ) {	
		$categories[] = [
			'slug'  => 'smb-section',
			'title' => __( 'Snow Monkey Blocks', 'snow-monkey-blocks' )
								. ' '
								. __( '[Sections]', 'snow-monkey-blocks' ),
		];
}
		return $categories;
	}
```

と言う感じで、既に登録されている場合はカテゴリー追加をしないってのはどうでしょう？
と言っても、フックの優先度的に先に実行してしまうと除外出来ないんで、一応の保護処理程度ですが…。

**Comment by inc2734** [comment]
`$slugs = array_column( $categories, 'slug' );`

ほー、↑こんなのあるんですね、知りませんでした。

重複する可能性は低いかなと思って特に処理いれてませんでしたが、やっぱりやったほうが良いですかねー。これって例えば Super Monkey Blocsk みたいなのがでてきて `smb` という名前でカテゴリー登録してきた場合、みたいなことですよね？

**Comment by kmix-39** [comment]
array_columnは便利っすよw
多次元配列の要素を取り出すのに使えます。

> smbと言う名前で

そうです。
まあ、重複した際にどうなるかは実際に試した方が分かりやすいと思います。
my_snow_monkeyにsmbをカテゴリー追加するフックとコードを適当に入れて重複させてみるのが手っ取り早いかと。
何か他のプラグインで同じslugのを多重に登録(重複)させてしまうとブロックカテゴリーの所がバグるんすよね…。なもんで、一応の対応をしておいても良いかなと思っています。
