### ISSUE TITLE
ブロックテンプレートを選択ブロックの下に挿入する

### ISSUE THREAD

**Issue by kmix-39** [inc2734/snow-monkey-blocks#208]
このissueは、こちらでやるので放置でOKです。（やるリストって事で）

-- MEMO --

`_block-templates.js` の `insertBlocks( parsedBlocks ); `
にindexを渡す。

https://github.com/WordPress/gutenberg/blob/07d99a7b45115dca4f5619b2f9dc3e1308a97f09/packages/block-editor/src/components/block-drop-zone/index.js#L72

参考は、この辺。

選択されているブロックがあればそのindexを取得して渡せば良い。
但し、選択されているブロックに親ブロックがある場合（innerblockの場合）は、rootを追いかけて最上位の親blockのindexを取得するようにする必要がある。

**Comment by inc2734** [comment]
https://github.com/inc2734/snow-monkey-blocks/pull/210
