### ISSUE TITLE
猿アイコン > ブロックは WP 5.3 以上では不要では？

### ISSUE THREAD

**Issue by inc2734** [inc2734/snow-monkey-blocks#212]
WP 5.3 からはインサーターのところにブロックの説明がでるので、猿アイコン > ブロックのタブは消して良いのではないかと。

@kmix-39 どう思います？

**Comment by kmix-39** [comment]
ブロックテンプレートの時にテンプレートのスクリーンショットを出すUI実装のテスト目的が理由で確か最初は作ったような…。

そこから、「使わないブロックを選択から外したい」「ブロックの配置された後のイメージを見たい」「ブロックの一覧あったら便利」→「公式でスクリーンショット付きで一覧ある」→「公式のスクリーンショット！それ、見ながらどのブロック使おうか決めたりしてる」と言うのが、3月の第一回ミートアップの飲み会時に話してたのもキッカケで、スクリーンショットとブロック一覧を入れたんでした。

選択から外す機能だけブロックマネージャーで出来るのでやらなかったんですが。

公式でもインサーターアンダーギーでブロックの説明は実装されたんですが、スクリーンショットはまだ無いので今の段階では置いといても良いかなと。スクリーンショットとかブロックプレビューが付いた際には思い切って外して良いです。

ブロックのプレビュー機能（出来れば自動で出るようなもん）は早く付いて欲しいですね…。スクリーンショットも用意するのも面倒な部分でわざわざ申し訳ないと思ってますし。

**Comment by inc2734** [comment]
あ、そうか、スクリーンショットですね。

いまちょっとみてたら、例えばカバーブロックとかはプレビューがでていました。

https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/cover/index.js

が、どうも再利用ブロックみたいにほんもののブロックを表示するっぽいので、きれいに表示させるのは難しい気がしますね…。

**Comment by kmix-39** [comment]
まだまだその部分はベータ機能みたいな感じしますよね。
exampleが例を出す設定なんでしょうけど、コレを今やるのも時期早々な気がしてならない…。

**Comment by inc2734** [comment]
とりあえず今は閉じます！
