### ISSUE TITLE
APIパスの整理

### ISSUE THREAD

**Issue by kmix-39** [inc2734/snow-monkey-blocks#217]
こちらでやりますー。

リファクタリングされているので、APIの関連リソース等の部分も統一したいと考えています。

/snow-monkey-blocks/v3/template-categories/
は
/snow-monkey-blocks/v5/block-templates-categories/

/snow-monkey-blocks/v3/block-templates/
は
/snow-monkey-blocks/v5/block-templates-panel/

に変更。（v3のエンドポイントは廃止って形で、v5にします）

SetupディレクトリのRestApi.phpは、RestAPI.phpに。
App/Api ディレクトリも統一で、 App/RestAPI に。

App/Api/TemplateCategories ディレクトリは App/RestAPI/BlockTemplatesCategories ディレクトリに変更
App/Api/BlockTemplates ディレクトリは App/RestAPI/BlockTemplatesCategories ディレクトリに変更
各RestAPIの呼び出しphp名は…EntryPoint.phpで統一

で、どうでしょう？
違和感ある部分は返信でお願いしますー。

**Comment by kmix-39** [comment]
'title' => _x( 'Headings', 'block-templates-category', 'snow-monkey-blocks' ),
		'slug'  => 'smb-block-templates-headings',
とかでblock-templatesと入れる、template とだけのディレクトリも block-templates にした方が良いのかもしれないっす。

理由： templateとblock-templatesがゴチャゴチャしているのを統一して、module-templates（component-template？Reactの処理を上手くtemplate化したもの）と区切りをつけれるようにしておきたい。

**Comment by inc2734** [comment]
https://github.com/inc2734/snow-monkey-blocks/pull/218 ← こちらマージしました！

> 'title' => _x( 'Headings', 'block-templates-category', 'snow-monkey-blocks' ),
> 'slug' => 'smb-block-templates-headings',
> とかでblock-templatesと入れる、template とだけのディレクトリも block-templates にした方が良いのかもしれないっす。

あーこれはしたほうが良い気がします。`block-templats-headings` なのか `block-template-headings` なのか迷いますね。僕のほうでファイル名変更したものとかもですが…

**Comment by inc2734** [comment]
Google で 「templates categories」で検索すると「もしかして template categories」と提案されるので、複数形 + 複数形は文法的に変なのかもしれません。なので単数形 + 複数形になるように変更をいれます。

**Comment by kmix-39** [comment]
なるほど。文法的に変なのは文法に合わせる方が良さそうですね。
この辺りの統一難しいですが、 block_template_と言うものから始まる = ブロックテンプレート って括りでまとめるしか無いって感じしますね
