### ISSUE TITLE
項目ブロックの「バナー」の色設定をクリアすると壊れたブロックになる

### ISSUE THREAD

**Issue by kmix-39** [inc2734/snow-monkey-blocks#246]
項目ブロックの「バナー」で色設定から文字色または背景マスクの色を選び、クリアした場合に壊れたブロックとなるようです。

**Comment by inc2734** [comment]
あー attibutes のデフォルトで色指定してるのにクリアすると undefined になるようにしてるからですかね…。デフォルトを空にするか、クリアするとデフォルト色になるようにしないとですね多分。ちょっとどっちが良いか考えます。

**Comment by kmix-39** [comment]
> クリアすると undefined になるようにしてるから

多分そうだと思います。
他にもこの手の文字色でundefindで壊れるのはありそうなので、ちょいちょいと他のブロックも時間ある時に壊れないか見ときます。
文字色の指定でデフォルトにするとか、個別にやると面倒な感じもするので、Helper作ってundefindの時にデフォルト色にするとか、まとめた処理とかも考える感じですかね？（悩む…
