### ISSUE TITLE
Gutenbergバージョン 7.1.0だとエディター内で見出しスタイルが出ない

### ISSUE THREAD

**Issue by kmix-39** [inc2734/snow-monkey-blocks#247]
.editor-styles-wrapper h2.rich-text などを入れると出るようになる。
githubで追いかけたところ、これが正しいスタイルっぽい？

.editor-styles-wrapper h2.rich-text.is-style-xxxxxx
ブロックのスタイルだとこう？

一応、今後の事もあるのでメモ程度のissue。

**Comment by kmix-39** [comment]
上のだとSMBの項目などのh2とかもスタイルがついてしまうので問題…。

その回避方法を調べたら、githubの公式のissueとかで

.editor-styles-wrapper div[data-type="core/heading"] > h2.rich-text.is-style-xxxxxx

で書けと言うような書き込みがあったので、どうやらエディター側はdata-typeでブロック名を渡すと良いっぽい。

表側はテーマに依存する。
Snow Monkeyだと
.p-entry-content > h2
となると思います。

**Comment by inc2734** [comment]
Snow Monkey v10 で解決したと思うのでクローズします！
