### ISSUE TITLE
Hookが通らない

### ISSUE THREAD

**Issue by kmix-39** [inc2734/snow-monkey-blocks#250]
分割前のSnow Monkey Blocksで通っていたHookが、分割後には通らなくなっている。
blocks.registerBlockTypeのHookとか。
分割前のSMBはHook通ってるし、wp-script側の問題かと思ったが、Coreのブロックは通っているからそうじゃないっぽい？

**Comment by inc2734** [comment]
その通らなくなったコードを教えてもらえますか？こちらでも試してみます。

> Coreのブロックは通っているからそうじゃないっぽい？

コアは各ブロックごとに `register_block_type()` されてないんですよね。なのでコアのブロックではなくてシンプルなカスタムブロックプラグインをつくって試してみないとわからないと思います。

**Comment by kmix-39** [comment]
どーも、とろゆにさんの制作されてるAdvanced Posts Blocks、了さんのHighlighting Code Blockとかも通らないんですよね。
wp-scripts側の問題なんじゃないかなーって気もします。

それで思い出して、さっきSnow Monkey Formsも試したんですが、それも通らなくなったから
分割とかではなくブロックエディター本体側か何か別の原因があるように感じてます。
とりあえず保留で。

コードは一応下記の感じっすね。

```
import {
	addFilter
} from '@wordpress/hooks';

function testRegisterBlockType( settings ) {
	console.log(settings.name);
	return settings;
}

addFilter(
	'blocks.registerBlockType',
	'my-guten/test/register-block-type',
	testRegisterBlockType
);

```

**Comment by inc2734** [comment]
とりあえず Snow Monkey Blocks の blocks.js に上記のコードをそのまま貼り付けてみたんですけど、ちゃんと動いているように見えます。

<img width="356" alt="スクリーンショット 2019-12-25 9 52 24" src="https://user-images.githubusercontent.com/1094306/71427468-489bb700-26fc-11ea-8f97-2a7ab1d34d41.png">

**Comment by kmix-39** [comment]
それ試すと動きますね。うーむ…？
同じプラグインからなら動くって事ですかねー…
別のプラグインでやると、正しく処理されないです。

Snow Monkey Blocksのblocks.jsに書いた場合ってSnow Monkey Formsのブロックもフック叩かれます？

**Comment by inc2734** [comment]
Forms はないですが、WooCommerce はありますね。単純にフックタイミングがはやすぎるのでは？

**Comment by kmix-39** [comment]
ぬあ…単純にフックタイミングっぽい…！！
gutenbergの6系か何かと違って、タイミングがscript読まれた際に変更されてるっぽいー…

以前は全ブロックが叩かれてたのですが、addFilterされるスクリプトを読むタイミングで読み終えてるブロックしか処理されてねー！！

すみません、理解しましたorz 単純な原因判明で泣きそう…

**Comment by inc2734** [comment]
PHP のフックでもあるあるですからねw 閉じます。
