### ISSUE TITLE
【最近の投稿 / 任意のタクソノミーの投稿】件数が0のときにメッセージをだしたい

### ISSUE THREAD

**Issue by inc2734** [inc2734/snow-monkey-blocks#266]
https://snow-monkey.2inc.org/forums/topic/%e4%bb%bb%e6%84%8f%e3%81%ae%e3%82%bf%e3%82%af%e3%82%bd%e3%83%8e%e3%83%9f%e3%83%bc%e3%81%ae%e6%8a%95%e7%a8%bf%e3%83%96%e3%83%ad%e3%83%83%e3%82%af%e3%81%ab%e8%a1%a8%e7%a4%ba%e3%81%99%e3%82%8b%e9%a0%85/

**Comment by kmix-39** [comment]
一応メモとしてコメント共有：
件数が 0 のものを選んだ際は `Block rendered as empty.undefined` と表示される（エディター内）
