### ISSUE TITLE
アプデ後、管理画面で「セクション（ブロークングリッド）」が崩れる

### ISSUE THREAD

**Issue by baccccck** [inc2734/snow-monkey-blocks#274]
アップデートお疲れ様です🙋そしていつも恐縮です

「セクション（ブロークングリッド）」で「縦方向の位置揃え」が崩れているような気がします

これは`<div class="smb-remove-button-wrapper">`に`display:flex`を適用すれば改善されるような気がします

よろしくお願いします

**Comment by inc2734** [comment]
編集画面内で、ってことですよね？こちらでは崩れているという印象は受けませんでしたが、具体的にどういう崩れが発生していますか？

**Comment by baccccck** [comment]
すいません。検証不足でした。
実際には崩れているというより「縦方向の位置揃え」が編集画面でうまく反映されていない感じです。
本来なら`align-items:`で「縦方向の位置揃え」が反映されると思うのですが`button > img`の高さがなぜかbuttonの高さに適用されていないためだと思います。
このbuttonに`height:100%`を指定したらうまく機能してくれました。
![2020-04-02_11h36_44](https://user-images.githubusercontent.com/60555934/78208030-4c4e8f00-74de-11ea-9edd-2d841dd72498.gif)

**Comment by inc2734** [comment]
キャプチャありがとうございます。「中央」なのにあきらかに下にずれてますね。なぜか僕の環境ではそのような見た目にならないのですが、button の高さが 36px 固定になっているのは問題ありそうだなと思います。

下記の CSS を足すとどうでしょうか？

```
.smb-remove-button-wrapper .image-button {
  height: auto;
}
```

**Comment by baccccck** [comment]
`wp-admin/load-styles.php`
で読み込まれている
`wp-includes/css/dist/components/style.css`
で
`.components-button{ height:36px; }`　が指定されてるのが原因でした汗
これをautoで上書きしたら解消されました！

wordpress5.4で最新のsnow monkeyテーマとblocksとeditorのプラグインを有効化の環境でした。
ブラウザはFirefoxです。
こちらの環境の問題でしたら、お騒がせしました。すいませんです。

**Comment by inc2734** [comment]
あ、なるほど、僕は Chrome で見てたので差があるのかもですね。CSS 的にはそこに height があるのは色々影響がありそうなので、auto になるように変更をいれますね。調査協力ありがとうございました！

**Comment by baccccck** [comment]
ブラウザの問題でした！ありがとうございます

**Comment by baccccck** [comment]
https://github.com/inc2734/snow-monkey-blocks/issues/255

たびたびすいません。これケミさんもissue出してくれてるやつで
このブロックだけじゃなく<button><img></button>となっている部分全てが崩れてしまっています。
（パネル等）

Chromeは<img>の要素にたいして<button>の位置が上に配置されるようですが
Firefoxは<img>の要素にたいして<button>が中央に配置されるようです。

**Comment by baccccck** [comment]
キタジマさんのソース反映でパネル等も大丈夫でした！
```
.smb-remove-button-wrapper .image-button {
  height: auto;
}
```

**Comment by inc2734** [comment]
次のアップデートで反映します！
