### ISSUE TITLE
Assets::_enqueue_block_scripts() does not return $block_content in admin context

### ISSUE THREAD

**Issue by richaber** [inc2734/snow-monkey-blocks#375]
Howdy @inc2734,

@megane9988 reported an incompatibility between Snow Monkey Blocks and WP Search with Algolia (reference https://github.com/WebDevStudios/wp-search-with-algolia/issues/76#issuecomment-689925944).

I took a moment to look into the issue, and traced it to the `Snow_Monkey\Plugin\Blocks\App\Setup\Assets` class.

In [`Snow_Monkey\Plugin\Blocks\App\Setup\Assets::__construct()`](https://github.com/inc2734/snow-monkey-blocks/blob/9.6.1/App/Setup/Assets.php#L22) line 22, the `_enqueue_block_scripts()` method is hooked to the `render_block` filter...

```
add_filter( 'render_block', [ $this, '_enqueue_block_scripts' ], 10, 2 );
```

The `_enqueue_block_scripts()` method does an [`is_admin()`](https://github.com/inc2734/snow-monkey-blocks/blob/9.6.1/App/Setup/Assets.php#L33-L35) check, and returns early if `true`.
_However_, the method does not return the `$block_content` that was passed in.

```
if ( is_admin() ) {
	return;
}
```

This causes an issue when Snow Monkey Blocks is installed alongside WP Search with Algolia, which expects to receive the return value on `the_content` filter when a post is saved in WP-Admin. This would likely have an impact on other plugins that also hook into `the_content` filter in the admin.

Since `_enqueue_block_scripts()` is running on a filter hook, it should return the original value in that early return statement.

```
if ( is_admin() ) {
	return $block_content;
}
```

**Comment by inc2734** [comment]
Thank you !!!
