### ISSUE TITLE
Snow Monkey Blocksの価格表、４つ以上の場合の表示が崩れる

### ISSUE THREAD

**Issue by inc2734** [inc2734/snow-monkey-blocks#47]
https://snow-monkey.2inc.org/forums/topic/snow-monkey-blocks%E3%81%AE%E4%BE%A1%E6%A0%BC%E8%A1%A8%E3%80%81%EF%BC%94%E3%81%A4%E4%BB%A5%E4%B8%8A%E3%81%AE%E5%A0%B4%E5%90%88%E3%81%AE%E8%A1%A8%E7%A4%BA%E3%81%8C%E5%B4%A9%E3%82%8C%E3%82%8B/

**Comment by kmix-39** [comment]
ブロックエディタの横幅によっては、３個の場合でも一部崩れてしまう？
（中の要素にもよる）

また、大抵の価格表サイトを見ると、横方向のスクロールがある様子。
横方向のスクロールを増やして幅を意識しない作りに変更した方が良いかもしれません。

**Comment by inc2734** [comment]
横スクロールを追加してみました。が、 `white-space: nowrap` にしないと普通に伸縮しちゃうみたいなのでそこが後方互換性的に大丈夫かはちょっと気になるかも。とりあえずこれで様子見しようと思います。
