### ISSUE TITLE
ボタンブロックのボタンをフルサイズにするとテキストがセンターにならない

### ISSUE THREAD

**Issue by kutsu123** [inc2734/snow-monkey-blocks#639]
お疲れ様です。
ボタンブロックのボタンサイズをフルサイズにするとテキストがセンターにいかない不具合を発見したのでお知らせします。
フルサイズになると、`display`が`block`になってるため、`justify-content: center` がうまく効かず、左に寄ってしまってました。

https://github.com/inc2734/snow-monkey-blocks/blob/1bf6f3dd51172299a6714e4c2810c59565bc9531/src/blocks/btn/style.scss#L60

**Comment by inc2734** [comment]
ありがとうございます！！

**Comment by inc2734** [comment]
下記のコミットで対応
https://github.com/inc2734/snow-monkey-blocks/commit/9cc113e438cefb82204a2a4999289c2e0fe93da4
