### ISSUE TITLE
セクション（ブロークングリッド）のコンテンツの背景色が一部設定できない

### ISSUE THREAD

**Issue by kutsu123** [inc2734/snow-monkey-blocks#641]
@inc2734 
お疲れ様です。セクション（ブロークングリッド）のコンテンツの背景色が一部設定できない不具合を発見したのでお知らせします。

### 不具合が起きる条件：
Snow Monkeyテーマ側の色パレットで色を選ぶ

### 原因と思われる要因：
Snow Monkeyテーマ側のパレットでは色番号ではなくCSS変数が設定されるため、JS側で背景色指定のための演算がうまく処理できず、結果色が設定されてないようです
![スクリーンショット 2023-02-15 10 45 46](https://user-images.githubusercontent.com/15826102/218908572-9bf565d8-0bef-4df7-a09a-b939205e5df4.png)

ここの処理？？
https://github.com/inc2734/snow-monkey-blocks/blob/36fd6d8c2fa1ee4212796b89c4a9bd9bf6035e55/src/blocks/section-break-the-grid/edit.js#L262

※自分の知識不足で具体的な修正PRができず報告だけですみません

**Comment by inc2734** [comment]
@kutsu123 ご報告ありがとうございます！！！

↓と同じ問題ですね…。
https://snow-monkey.2inc.org/2023/02/14/snow-monkey-editor-v9-1-2/

蛍光ペンの場合は、選んだ色が CSS 変数だった場合は透過せずにそのままを使うようにしました。そうするとアクセントカラーをあとで変更したときに適用済みの蛍光ペンの色も変わるので。

ブロークングリッドの場合はどうするか悩みますね……。蛍光ペンは透過しなくてもまぁそんなに閲覧に支障はないので上記のような対応をしましたが、ブロークングリッドの場合は見た目の印象に強く影響すると思うので…。一応 CSS 変数の中身を参照してカラーコードを抜き出してそれを適用させるということはできて、そうすれば透過度も適用できるのですが、その場合はあとでアクセントカラーを変えたとしても、適用した背景色は変わらずにそのままということになります（カラーコードとして HTML に埋め込まれちゃうので）。

まぁ過去バージョンではカラーコードを保存していたのでそれでも良いっちゃ良いと思うのですが…使っててどっちが良さそうとかありますかね？

**Comment by kutsu123** [comment]
@inc2734 
対応の重複と同じ指摘をしてしまってすみません！！

> まぁ過去バージョンではカラーコードを保存していたのでそれでも良いっちゃ良いと思うのですが…使っててどっちが良さそうとかありますかね？

確かに過去だとカラーコードが結果入ってたので、アクセントカラーとか変更しちゃう可能性があるのを見越しても、色番号で最終的に格納されるで良いような気がします。（もちろん変数の値ちょろっと変えれば一発で全体変えられるという技が使えなくなるデメリットありますが）
ブロック入れたあと、なんとなくで設定画面ポチポチで変えてくことのほうが多いので、設定画面に表示されてる項目でできることは、できたほうが操作のストレスが溜まりにくいなと思ってます。（たぶんユーザーさん、カラーパレットの「テーマ」と「デフォルト」の違い気づいてる人あまりいなくて、なんか押した色によって挙動が違うと戸惑いそうだなと思います）

**Comment by inc2734** [comment]
> たぶんユーザーさん、カラーパレットの「テーマ」と「デフォルト」の違い気づいてる人あまりいなくて、なんか押した色によって挙動が違うと戸惑いそうだなと思います

あー確かにそうですよね…。ちょっとカラーコードを抽出する形でやってみます。ありがとうございます！
