### ISSUE TITLE
セクション（ブロークングリッド）で画像のマスクが設定できない

### ISSUE THREAD

**Issue by kutsu123** [inc2734/snow-monkey-blocks#642]
@inc2734 
お疲れ様です。セクション（ブロークングリッド）で画像のマスクが設定できてない不具合を発見したのでお知らせします

### 起きてる不具合
- カラーパレットから色を選択してもCSS変数`--smb-section-break-the-grid--mask-color`に情報が格納されない（初期値のまま）
- カラーパレットから色を選択すると出てくる不透明度の設定を設定すると`--smb-section-break-the-grid--mask-opacity`にはなぜかpxつきで値が出力されてしまってる
![スクリーンショット 2023-02-15 11 23 47](https://user-images.githubusercontent.com/15826102/218912309-55cb47f4-f9c1-4f47-88df-7bab308a7957.png)

https://github.com/inc2734/snow-monkey-blocks/blob/36fd6d8c2fa1ee4212796b89c4a9bd9bf6035e55/src/blocks/section-break-the-grid/edit.js#L263

**Comment by inc2734** [comment]
@kutsu123 ご報告ありがとうございます！！！

↓と同じ問題ですね…。
https://snow-monkey.2inc.org/2023/02/14/snow-monkey-editor-v9-1-2/

蛍光ペンの場合は、選んだ色が CSS 変数だった場合は透過せずにそのままを使うようにしました。そうするとアクセントカラーをあとで変更したときに適用済みの蛍光ペンの色も変わるので。

ブロークングリッドの場合はどうするか悩みますね……。蛍光ペンは透過しなくてもまぁそんなに閲覧に支障はないので上記のような対応をしましたが、ブロークングリッドの場合は見た目の印象に強く影響すると思うので…。一応 CSS 変数の中身を参照してカラーコードを抜き出してそれを適用させるということはできて、そうすれば透過度も適用できるのですが、その場合はあとでアクセントカラーを変えたとしても、適用した背景色は変わらずにそのままということになります（カラーコードとして HTML に埋め込まれちゃうので）。

まぁ過去バージョンではカラーコードを保存していたのでそれでも良いっちゃ良いと思うのですが…使っててどっちが良さそうとかありますかね？

**Comment by inc2734** [comment]
ありがとうございます！色が反映されないのはシンプルなミスでした…。不透明度は WordPress のいつ頃からかのバージョンから、保存された値が数値だと自動的に`px`が補完されてしまうことがあって、その影響ですね…。他の場所は文字として保存することで対応していたのですがここは漏れてしまっていました。ご報告ありがとうございます！
