### ISSUE TITLE
情報ブロックを入れ子にして利用した場合にラベルの縦位置中央揃えが子側の情報ブロックに影響してしまう

### ISSUE THREAD

**Issue by kutsu123** [inc2734/snow-monkey-blocks#646]
@inc2734 
お疲れ様です。
なかなかないレアケースだとは思いますが、意図しない表示を見つけたためお知らせします。

## 概要など
- 情報ブロックの行の中に情報ブロックを設置する
- 親側の情報ブロックの「ラベルの縦位置」を「中央揃え」に設定
- 子側の情報ブロックのラベルの縦位置も「中央揃え」になってしまう

![スクリーンショット 2023-02-20 15 19 40](https://user-images.githubusercontent.com/15826102/220027833-5747a678-448b-4f0a-95b1-81b9e041530c.png)

`.smb-information:not([data-sm-split-column=true])[data-label-vertical-align=middle] .smb-information__item>.c-row>.c-row__col:first-child` のセレクタを `.smb-information:not([data-sm-split-column=true])[data-label-vertical-align=middle] >smb-information__body > .smb-information__item>.c-row>.c-row__col:first-child` まで指定を厳格化するか、`.smb-information:not([data-sm-split-column=true]) .smb-information__item>.c-row>.c-row__col:first-child` にデフォルトで`justify-content: flex-start`を当てておくかするときっと解消するのかなと思ってます

**Comment by inc2734** [comment]
あーなるほどです。入れ子は考慮してなかったので、他のブロックも似たようなのがあるかもですね…ひとまず確認して修正入れます。ご報告ありがとうございます！

**Comment by inc2734** [comment]
@kutsu123 セレクタをびっちり当てないとダメっぽかったので、その方向で変更を入れました。ラベルの上下位置だけじゃなくて左右位置も同様の問題があったのでそちらも同じ変更を入れました。

結果的に詳細度がかなり上がってしまっているので、影響がでちゃうかなと思います…。改めて見るともともとの設計がよろしくなかったですね…大影響でちゃうので今更変更はできないですが…CSS ムズカシイ😱

**Comment by kutsu123** [comment]
@inc2734 
ご対応ありがとうございます！
なんというか、CSS本当に難しいですよね（特にブロックみたいな汎用的に使うものは特に）
変更内容についても承知です　いつもご対応ありがとうございます

**Comment by inc2734** [comment]
マージしてリリースします！

**Comment by kutsu123** [comment]
こちらご対応ありがとうございました。
確認遅くなってすみません。親側のラベルの位置変更しても、子側には影響ないの確認しました。
とても助かりました。ありがとうございました
