### ISSUE TITLE
FAQブロックの「Q」や「A」のラベルとテキストのツラが揃ってないように見える

### ISSUE THREAD

**Issue by kutsu123** [inc2734/snow-monkey-blocks#648]
@inc2734 
お疲れ様です。
FAQブロックの「Q」や「A」のラベルのline-heightが大きいせいか、ラベル右に表記している各テキストと上部のツラが揃ってないように見えてしまってます。
イレギュラーな感じになってしまいそうですが、ここだけ計算式ではなく絶対値（1など）で設定してしまっても良いかなと思いました。

例：
https://shop.m-g-n.me/faq/

![スクリーンショット 2023-02-22 15 34 00](https://user-images.githubusercontent.com/15826102/220542069-942a4783-3f51-420b-8098-045ced92a4a5.png)

（そもそも、今全面的な文字サイズについて、あれこれ調整をされてるところで大変だと思いますので、その後、検討の余地があったらご検討いただくぐらいで大丈夫です）

**Comment by inc2734** [comment]
@kutsu123 確かに！！ここは `line-height: 1` にします！

**Comment by inc2734** [comment]
あ、でも
https://github.com/inc2734/snow-monkey/issues/1319
の流体タイポグラフィが適用された場合、スマホではちょびっと文字サイズが小さくなるので、`line-height: 1.05` くらいがちょうど良いかも。

**Comment by kutsu123** [comment]
確かに 1.05ぐらいでいいかも
