### ISSUE TITLE
目次ブロックのデフォルトのタイトルについて

### ISSUE THREAD

**Issue by kutsu123** [inc2734/snow-monkey-blocks#653]
@inc2734 
お疲れ様です。
v18.1.0から目次ブロックのタイトル（これまで「目次」が表記されていた箇所）が任意で書き換えられるようになりましたが、なにも書き換えてない投稿についてタイトル何も入っておらず、これまで目次と表示されていた箇所が何も表示されなくなりました。

- v18.1.0以前のバージョンで目次ブロックを挿入した投稿を作成・公開（この時点ではタイトルには"目次"が入っている）
- v18.2.0の環境で作成した投稿を表示するとタイトルには何も入っていない
- その後、編集画面を開くと目次というテキストは見えてはいるし、H2内にテキストは入っている。だがそのままプレビューや更新をおこなっても実際に「目次」と表記されたタイトルは表示されない
- 編集画面でタイトル部に文字の入力を行った時点で、タイトルに表記された文字が実際のページにも反映される

こちら仕様か不具合かがわからないのですが、もし可能であれば、デフォルトには目次の表記があると、前と同じままで運用できるので助かるという気持ちがあります（難しい注文だったらもちろん無視ください）

※この現象、クライアントさんのサイトで偶然見つけたもので、もし普通はこのようなこと起きなかったらすみません

**Comment by inc2734** [comment]
ご報告ありがとうございます！
タイトルを変えれるようにしたときに未設定の場合は「目次」となるようにしたつもりだったのですが確認があまかったかもですね…。来週になると思いますが確認してみます！
