### ISSUE TITLE
アラートブロックの!アイコンが編集画面で表示されていない

### ISSUE THREAD

**Issue by kutsu123** [inc2734/snow-monkey-blocks#658]
お疲れ様です。
ちょっと気になった箇所があったので一旦報告させてもらいます（優先度は低いものかなと思ってます）

アラートブロックでは設定パネルでタイトル横に表示するアイコンを選択できるかと思うのですが、`circle-exclamation`（○の中に!が入ったタイプ）のアイコンを選択すると、タイトル横には表示されませんでした。

- この現象が起きるのは編集画面のみ（フロント側はアイコン表示されてます）
- `circle-exclamation` 以外のアイコンは編集画面上でもアイコンが表示されてます

![スクリーンショット 2023-03-11 12 35 57](https://user-images.githubusercontent.com/15826102/224463243-8846a909-8018-46a4-9a83-16578dcd9da1.png)

**Comment by inc2734** [comment]
あ、これ僕も issue #652 立てていたのですが、気づいたらならなくなってたんで閉じたんですよね。feature/#651 ブランチでビルドしてもらうと、直ったりしてないですかね？

**Comment by kutsu123** [comment]
重複issueですみません
feature/#651ブランチに切り替えて、npm run buildして確認してみたのですが、私の環境だと!マークでてないままでした

https://user-images.githubusercontent.com/15826102/224585244-2cdf5183-9229-48e4-bc37-077d9536c81a.mov

**Comment by inc2734** [comment]
あれ…
確認します！！

**Comment by inc2734** [comment]
試してみましたが表示されてしまいました。

https://user-images.githubusercontent.com/1094306/224585967-672e3eb7-21ed-4f26-9061-90f8b68f0981.mp4

WordPress のバージョンとか、Snow Monkey のバージョン、node の関係で僕の環境でしかうまくビルドできないようになっちゃってるとか色々考えられるので、6.2 時点で一旦全部リリースして環境が整ってから、まだ再現するようなら改めて調査しようと思います。

とりあえずそれまで issue は開けておきます！
