### ISSUE TITLE
【価格表】カラムサイズの設定について効くときと効かないときがある

### ISSUE THREAD

**Issue by kutsu123** [inc2734/snow-monkey-blocks#680]
@inc2734 
お疲れ様です。
価格表ブロックについて、カラムサイズの設定項目がありますが、効くときと効かないときがあります。
（仕様なのか、意図しない挙動なのかがわからないのですが、気になったのでissueたてさせてもらいました　仕様だったらすみません）

プラグインバージョン：
Snow Monkey Blocks v19 RC2

詳細：
- 価格表の子アイテムが3つまでのときは、カラムサイズに何を設定しても無視される
- 価格表の子アイテムが4つ以上のときに、カラムサイズに指定したサイズになる

CSSにて`[data-has-items="xx"]`の指定のほうが有効になっており、data-has-items は3つのときまでのスタイルまでしかCSSが存在しないので、4つ以上のときに`.smb-pricing-table--col-size-1-xx`の指定のスタイルが読み込まれるようになっていました。

**Comment by inc2734** [comment]
ご報告ありがとうございます！

「自動」のときに3つまでは幅が強制されるのは試用みたいです。
https://github.com/inc2734/snow-monkey-blocks/issues/377#issuecomment-706185955

ただ、サイズ指定しているのに効かないのは詳細度からくる不具合ですね…。修正します！
