### ISSUE TITLE
要望：【情報】ラベルの文字色の色の設定があると親切そう

### ISSUE THREAD

**Issue by kutsu123** [inc2734/snow-monkey-blocks#681]
お疲れ様です。Snow Monkey Blocks v19 RC2を触ってて、こういう機能もあったら親切かなって思ったものがあったので、issue立てさせてもらいました。（特になくて困ってるとかじゃなくて、あったらより親切かもと思ったぐらいなので、その気になったら検討ぐらいで大丈夫です）

対象：情報ブロック

内容：
v19からラベルの背景色が選べるようになったので、それに合わせてラベルの文字色も設定からできるようになったらいいなと思いました（背景色を暗めの色にしたときに文字色を白に設定したいなということがあるので）

その他：
もし、実装してもいいかなって思った際には、私がまたコード修正してみてPRするみたいな方法とってみてもいいでしょうか？
もちろんキタジマさん自身で対応してしまうでもOKです（その方が効率がめっちゃいい）

**Comment by inc2734** [comment]
確かに！これはやりましょう。

> 私がまたコード修正してみてPRするみたいな方法とってみてもいいでしょうか？

それは常にウェルカムです！
もしやるとしたら、

1. block.json にテキスト色用の attribute を追加
2. [ここ](https://github.com/inc2734/snow-monkey-blocks/blob/feature/%23651/src/blocks/information/edit.js#L106-L129)にテキスト色用の設定を追加
3. [ここ](https://github.com/inc2734/snow-monkey-blocks/blob/feature/%23651/src/blocks/information/edit.js#L74-L77) と [ここ](https://github.com/inc2734/snow-monkey-blocks/blob/feature/%23651/src/blocks/information/save.js#L25-L28) にテキスト色用の style 属性を追加

という流れになると思います。ちょっと今は unitone のやりかけの作業を潰しているところなので、僕がやるとしたら v19 リリース後に 19.1 での対応になると思います。

**Comment by kutsu123** [comment]
@inc2734 
お疲れ様です。ちょっとやってみたら、ラベルのテキスト色設定追加できたので、PR出せせていただきました
お暇になったらで全然構わないので、レビューしていただけますとありがたいです。

PR：#682
- masterにPR出してしまったのですが、違うブランチのほうがよければ出し直します 
- 翻訳ファイルがこちらだと作れないので、すみません翻訳は手をつけてません
