### ISSUE TITLE
19.3.0でサイト表示にエラーが発生、バージョン 19.3.1へダッシュボードより更新できず

### ISSUE THREAD

**Issue by nukaga** [inc2734/snow-monkey-blocks#704]
WordPress 6.2.2
PHP バージョン 7.4.33

19.3.0でエラーが発生、バージョン 19.3.1にダッシュボードより更新するが、更新成功と出ても実際は更新されずエラーが出続けます。
現状バージョン 19.2.1にダウングレードして使用中です。

表示されたエラーメッセージは以下です。こちらの環境のせいかもしれませんがご報告します。

`Parse error: syntax error, unexpected ')', expecting variable (T_VARIABLE) in /home/academicweb/www/arg-corp.jp/site/wp-content/plugins/snow-monkey-blocks/App/DynamicBlocks.php on line 30`

**Comment by inc2734** [comment]
19.3.1 で修正済みのはずですが、エラーのせいで更新がコケるのかもしれませんね…。
https://ja.wordpress.org/plugins/snow-monkey-blocks/
↑から zip ファイルをダウンロードし、ダッシュボードからアップロード、それでもダメなら FTP ソフトで上書きアップロードしてみてください><
