### ISSUE TITLE
最近の投稿ブロックで過去にはなかったmeta要素がデフォルトで表示されてしまう

### ISSUE THREAD

**Issue by kutsu123** [inc2734/snow-monkey-blocks#714]
@inc2734 
お疲れ様です。
たぶんSnow Monkey Blocks v19.3 あたりの影響だと思うのですが、過去のバージョンで作成したページ内の「最近の投稿ブロック」で、これまで表示されてなかったmeta要素が表示されてしまう現象がありました。
（ただ、必ず起きる現象ではなく、ひょっとしたらすごい特殊な環境下だけかもしれません）

## 確認した現象
「テキスト2」の場合に、これまではmetaの著者表示がなかったが、最新版だと著者表示がされてしまってる
https://demo.rui-jin-en.com/r002-lp-a/news

- 保存されたページの編集画面を確認するとブロックの設定欄では著者情報表示はONになっている
- 新規投稿から最近の投稿ブロックを挿入、その後テキスト2にレイアウト指定を行うと著者情報表示はOFFになっている

※すみません、一旦報告だけさせてもらってます

**Comment by inc2734** [comment]
うおーそうか、レイアウトを切り替えたときは、そのレイアウトの初期値として決められている表示・非表示設定がなされるのですが、すでに設置済みのものについてはその初期値の設定がおこなわれずに全部でちゃう、みたいな感じのようです。ちょっとどう対処できるか調査してみます。ご報告ありがとうございます！

**Comment by inc2734** [comment]
@kutsu123 Snow Monkey 側の調整も必要だったため、Snow Monkey と Blocks 両方に修正を入れてそれぞれの master に push しました！お手間でなければ Snow Monkey と Blocks を pull ＆ビルドして試してみてください！（お手間であればこちらで全然 zip つくってお渡しするので言ってください）

**Comment by kutsu123** [comment]
@inc2734 
ご確認ご対応などありがとうございます！！

最新のコミットのもので試してみたところ、最近の投稿ブロック（あと投稿アーカイブも）の表示内容は前と同様になりました（著者表示なくなりました）

**Comment by inc2734** [comment]
@kutsu123 ありがとうございます！こちらでみた感じでも問題なさそうなので、これでマージしてクローズします！またあとでおかしなところをもし見つけたら教えてください！
