### ISSUE TITLE
特定のclass（is-layout-constrained）があるセクションで背景色が表示されない

### ISSUE THREAD

**Issue by kutsu123** [inc2734/snow-monkey-blocks#741]
@inc2734 
お疲れ様です。
WordPress6.3環境での動作確認をしてて、１つこれまでと挙動が違っている箇所があったのでお知らせします
（私の環境が特殊な状態とかだった場合は余計な報告ですみません）

## 検証環境

- WordPress 6.4 RC4
- Snow Monkey v25.0.0 Beta1
- Snow Monkey Blocks v20.0.0 Beta2

## 現象詳細
セクションブロックにclass「is-layout-constrained」が付与されてると、背景色（固定・移動）が表示されなくなります。
背景色や文字のdivは、通常`position: absolute` なのですが、is-layout-constrainedが付与された場合はCSSが上書きされて`position: relative`になってしまい、領域が確保できてないのが原因のようです。

そしてすみません 「is-layout-constrained」がどのような条件で付与されるのかが自分ではわからず・・・
もしものすごく特殊な条件とか、過去間違った手順でこちらで付与されてしまったclassとかだったらすみません

https://github.com/inc2734/snow-monkey-blocks/assets/15826102/73e5d940-810a-43ab-ad67-d8e80fc5950e
![スクリーンショット 2023-08-08 16 59 29](https://github.com/inc2734/snow-monkey-blocks/assets/15826102/163a19e6-46b8-4e88-94dc-e7158642984d)

**Comment by inc2734** [comment]
あ、もしかしたら Snow Monkey の master ブランチだとちゃんと動作したりしないですかね…？

**Comment by kutsu123** [comment]
@inc2734 
masterの最新で試したら背景つきました！！

**Comment by kutsu123** [comment]
@inc2734 
トピックの報告とズレた内容を質問してしまいすみません

**Comment by kutsu123** [comment]
@inc2734 
トピずれの内容で追加質問すみません！！（もしふさわしくないようであれば別issue立てます）

.is-layout-constrained>:not(:first-child) で margin-top がつくように設定されてるのですが、こちらはイキですよね？？
（この背景でなかったセクション内に入れた各要素でmargin-topがつくようになってしまったので、取り消すCSSを書くべきか悩んでいます）

**Comment by inc2734** [comment]
@kutsu123 

> セクション内に入れた各要素でmargin-topがつくようになってしまったので

もともと下記の CSS があって、

<img width="368" alt="スクリーンショット 2023-08-08 19 05 58" src="https://github.com/inc2734/snow-monkey-blocks/assets/1094306/ebb22b1b-ed17-47ea-8622-90629f8eec32">

これを .is-layout-constrained のときとなるように置き換えたつもりだったのですが、（セレクタは置いといて）当たっているスタイル自体が変わっているということですかね？

**Comment by kutsu123** [comment]
@inc2734 
ご返答ありがとうございます。
セクションの場合だと、今までだと .smb-section__inner にはmargin-topがなかったのですが、今回のケースだとmargin-topがついてしまうので（backgroundのdivの次に来てしまってる故）、現行のものより上部の余白値が大きめになってしまっています
というか、セクション内の各要素って説明めっちゃ下手くそ・・・ わかりずらい文章で聞いてしまってすみません（汗）


![スクリーンショット 2023-08-08 21 11 52](https://github.com/inc2734/snow-monkey-blocks/assets/15826102/a09c9a17-0f3e-4ce0-9057-18767f3f5ca8)
▲なんか検証ツールの文字小さくてわかりずらくてすみません（設定どこで変えるんだろう・・・）

**Comment by inc2734** [comment]
@kutsu123 
なるほど！ですがなんか僕の環境とはレイアウト用クラスの付き方が違いますね…。

僕の場合だと、`.smb-section` のところには `.is-layout-constrained` がついてなくて、 `.smb-section__body` のところに `.is-layout-constrained` がついています。

<img width="1371" alt="スクリーンショット 2023-08-08 23 53 20" src="https://github.com/inc2734/snow-monkey-blocks/assets/1094306/161bde4c-c7b9-420b-b63b-4830a8785bfb">

バージョンまわりは一緒だと思うのですがなんでだろう…。

**Comment by kutsu123** [comment]
@inc2734 
度々のご確認などありがとうございます。
あらためて確認してみたら、同じセクションでも新しく追加した方はちゃんとbody側にclassが当たってました
今回の現象が起きたセクション（親側にclassがついちゃう）は、結構前に作ったページの中に入ってるものなので、なにか特殊なのかもしれません。

環境については、別口でお送りいたします　少々お待ちください

**Comment by kutsu123** [comment]
@inc2734 
お疲れ様です。ご対応ありがとうございます。
私の方で不具合が起きてたブロックまさしく子ブロックない状態でした！！
ご対応ありがとうございます。無事セクションのbody側に「is-layout-constrained」つくようになりました
