### ISSUE TITLE
画像の解除ボタンのラベル文字が表示されていない

### ISSUE THREAD

**Issue by kutsu123** [inc2734/snow-monkey-blocks#742]
@inc2734 
お疲れ様です。
（こちらコアの方の不具合だったらすみません）

WordPress6.3の環境だとこれまで表示されてた画像解除ボタンの「解除（Relese）」の文言が表示されてませんでした。
念のため報告しておきます

![スクリーンショット 2023-08-08 18 12 16](https://github.com/inc2734/snow-monkey-blocks/assets/15826102/960bc17a-58c1-4324-a27f-4c976e82ed0a)

**Comment by inc2734** [comment]
ほんとだ！確認します！
