### ISSUE TITLE
「続きを読む」ブロックのボタンがフルサイズにならない

### ISSUE THREAD

**Issue by kutsu123** [inc2734/snow-monkey-blocks#755]
@inc2734 
お疲れ様です。
「続きを読む」ブロックを触ってて気づいたのですが、ボタンのサイズを「フルサイズ」にしたときにフルサイズにならない現象が起きています。
button要素には`.smb-btn--full`が指定されており、Witdhもきちんと指定はされてるのですが、このボタンの親である`smb-btn-box__btn-wrapper`がflexboxの子どもで特にmax-widthやflex-basisで領域を指定しておらず、領域が100%確保できてないせいかもしれないです（違ったらすみません）

**Comment by inc2734** [comment]
@kutsu123 ご報告ありがとうございます。確認します！
