### ISSUE TITLE
ボックスブロックの枠線の数値を消すとエラーが起きる

### ISSUE THREAD

**Issue by kutsu123** [inc2734/snow-monkey-blocks#757]
@inc2734 
お疲れ様です。
先日ボックスブロックを使っていて気づいたのですが、ブロックの設定で枠線の入力欄を空にするとエラーになってしまいます。
枠線取りたいなあっていうときに、ついつい数値を消してしまう癖があるので、空の値も許容してくれるような形だと助かるなと思いました。

（すみません、自力でコード直せないかとチャレンジしたのですが、どこ直せばいけるのか分からず断念しました。　Issue立てだけしてしまってすみません）

https://github.com/inc2734/snow-monkey-blocks/assets/15826102/53c7070d-8acf-4706-a048-53d7f377f3fc

**Comment by inc2734** [comment]
ご報告ありがとうございます！確認してみますね。

**Comment by inc2734** [comment]
修正しました！

**Comment by kutsu123** [comment]
ご対応ありがとうございます！！
空の状態だと、エラー起こさず枠線がなくなること確認しました。
